In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import math
import matplotlib.pyplot as plt
import matplotlib as mpl
import PublicFunctions as pf

# Read

The data was downloaded from Zillow Research (https://www.zillow.com/research/data/ --> Inventory --> New Listings (Raw, All Homes, Montly View)) as the .csv file given here. Column headers represent the last day of the month, which we simply refer to as the month, i.e., column '2018-1-31' is 'January 2018.'

In [2]:
df = pd.read_csv('Metro_new_listings_uc_sfrcondo_month.csv')
df

RegionID  SizeRank       RegionName RegionType StateName  1/31/2018  \
0      102001         0    United States    country       NaN   327792.0   
1      394913         1     New York, NY        msa        NY    14997.0   
2      753899         2  Los Angeles, CA        msa        CA     8274.0   
3      394463         3      Chicago, IL        msa        IL     8795.0   
4      394514         4       Dallas, TX        msa        TX     7848.0   
..        ...       ...              ...        ...       ...        ...   
884    753929       923       Zapata, TX        msa        TX        NaN   
885    394743       924    Ketchikan, AK        msa        AK        NaN   
886    753874       925        Craig, CO        msa        CO       19.0   
887    394767       926       Lamesa, TX        msa        TX        NaN   
888    395188       927       Vernon, TX        msa        TX        NaN   

     2/28/2018  3/31/2018  4/30/2018  5/31/2018  ...  11/30/2021  12/31/2021  \
0     381284.0   490780.0   529164.0   554878.0  ...    315174.0    215175.0   
1      22401.0    23484.0    26845.0    26302.0  ...     12043.0      6911.0   
2       9505.0    10523.0    11052.0    11871.0  ...      6591.0      4466.0   
3      11937.0    17632.0    17154.0    17315.0  ...      8726.0      5380.0   
4       8186.0    11131.0    12357.0    12362.0  ...      7995.0      5751.0   
..         ...        ...        ...        ...  ...         ...         ...   
884        NaN        NaN        NaN        NaN  ...         NaN         NaN   
885        NaN        NaN        NaN        NaN  ...         NaN         NaN   
886       25.0       24.0       34.0       51.0  ...        14.0        10.0   
887        NaN        NaN        NaN        NaN  ...         NaN         NaN   
888        NaN        NaN        NaN        NaN  ...         NaN         NaN   

     1/31/2022  2/28/2022  3/31/2022  4/30/2022  5/31/2022  6/30/2022  \
0     253159.0   284434.0   385837.0   417512.0   440501.0   474768.0   
1       9214.0    11516.0    16027.0    16427.0    17057.0    17237.0   
2       6533.0     7619.0     9115.0     9312.0     9413.0     9847.0   
3       7253.0     8960.0    12644.0    13390.0    13876.0    14605.0   
4       6202.0     6155.0     8376.0     9647.0    10372.0    12367.0   
..         ...        ...        ...        ...        ...        ...   
884        NaN        NaN        NaN        NaN        NaN        6.0   
885        NaN        9.0       12.0       15.0        7.0        9.0   
886       14.0        9.0       20.0       30.0       33.0       22.0   
887        NaN        NaN       13.0        6.0        8.0       11.0   
888        NaN        NaN        5.0        6.0        8.0        7.0   

     7/31/2022  8/31/2022  
0     409400.0     361392  
1      14057.0      11642  
2       8691.0       7464  
3      12056.0      10313  
4      10742.0       8544  
..         ...        ...  
884        NaN          6  
885       13.0          7  
886       20.0         28  
887       10.0         18  
888        6.0         12  

[889 rows x 61 columns]

# Isolate the data for the team

In [3]:
team = 0
row = df.iloc[team]
row

RegionID             102001
SizeRank                  0
RegionName    United States
RegionType          country
StateName               NaN
                  ...      
4/30/2022            417512
5/31/2022            440501
6/30/2022            474768
7/31/2022            409400
8/31/2022            361392
Name: 0, Length: 61, dtype: object

Calculate the monthly averages for years 1 thru 4. 

In [4]:
y1avg = np.random.normal(0,1,1) #Must change this, it is curently just random
y1avg

array([-0.0163782])

In [5]:
y2avg = np.random.normal(0,1,1) #Must change this, it is curently just random
y2avg

array([1.73435088])

In [6]:
y3avg = np.random.normal(0,1,1) #Must change this, it is curently just random
y3avg

array([0.21324548])

In [7]:
y4avg = np.random.normal(0,1,1) #Must change this, it is curently just random
y4avg

array([-0.70523674])

# Forecast Using the Decomposition Method

Calculate the seasonal index for each season each year, and then the average (over the two years) for each season.

In [8]:
values = [np.random.randint(1,101,12)/50,
         np.random.randint(1,101,12)/50,
         np.random.randint(1,101,12)/50,
         np.random.randint(1,101,12)/50]#Must change this, it is curently just random
SI = pd.DataFrame(values, columns = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'], index = ['Year 1', 'Year 2', 'Year 3', 'Year 4'])
SI.loc['Average'] = SI.mean()
SI

January  February  March  April   May   June   July  August  \
Year 1     1.160      1.46  1.120  1.620  0.34  0.640  0.600    1.34   
Year 2     0.700      1.14  1.800  0.460  0.66  0.780  1.480    0.38   
Year 3     1.440      0.24  0.720  1.440  1.06  0.620  0.100    1.00   
Year 4     0.120      2.00  1.820  1.660  0.74  1.260  0.800    1.40   
Average    0.855      1.21  1.365  1.295  0.70  0.825  0.745    1.03   

         September  October  November  December  
Year 1       1.560    1.360     1.400      1.84  
Year 2       0.280    1.640     1.440      1.06  
Year 3       1.800    1.300     0.020      0.18  
Year 4       0.420    0.840     0.560      0.68  
Average      1.015    1.285     0.855      0.94

Deseasonalize the data.

In [9]:
y_dm = np.array(row[5:53])
y_dm[0] = y_dm[0]/SI.loc['Average']['January']
y_dm[1] = y_dm[1]/SI.loc['Average']['February']
y_dm[2] = y_dm[2]/SI.loc['Average']['March']
y_dm[3] = y_dm[3]/SI.loc['Average']['April']
y_dm[4] = y_dm[4]/SI.loc['Average']['May']
y_dm[5] = y_dm[5]/SI.loc['Average']['June']
y_dm[6] = y_dm[6]/SI.loc['Average']['July']
y_dm[7] = y_dm[7]/SI.loc['Average']['August']
y_dm[8] = y_dm[8]/SI.loc['Average']['September']
y_dm[9] = y_dm[9]/SI.loc['Average']['October']
y_dm[10] = y_dm[10]/SI.loc['Average']['November']
y_dm[11] = y_dm[11]/SI.loc['Average']['December']
y_dm[12] = y_dm[12]/SI.loc['Average']['January']
y_dm[13] = y_dm[13]/SI.loc['Average']['February']
y_dm[14] = y_dm[14]/SI.loc['Average']['March']
y_dm[15] = y_dm[15]/SI.loc['Average']['April']
y_dm[16] = y_dm[16]/SI.loc['Average']['May']
y_dm[17] = y_dm[17]/SI.loc['Average']['June']
y_dm[18] = y_dm[18]/SI.loc['Average']['July']
y_dm[19] = y_dm[19]/SI.loc['Average']['August']
y_dm[20] = y_dm[20]/SI.loc['Average']['September']
y_dm[21] = y_dm[21]/SI.loc['Average']['October']
y_dm[22] = y_dm[22]/SI.loc['Average']['November']
y_dm[23] = y_dm[23]/SI.loc['Average']['December']
y_dm[24] = y_dm[24]/SI.loc['Average']['January']
y_dm[25] = y_dm[25]/SI.loc['Average']['February']
y_dm[26] = y_dm[26]/SI.loc['Average']['March']
y_dm[27] = y_dm[27]/SI.loc['Average']['April']
y_dm[28] = y_dm[28]/SI.loc['Average']['May']
y_dm[29] = y_dm[29]/SI.loc['Average']['June']
y_dm[30] = y_dm[30]/SI.loc['Average']['July']
y_dm[31] = y_dm[31]/SI.loc['Average']['August']
y_dm[32] = y_dm[32]/SI.loc['Average']['September']
y_dm[33] = y_dm[33]/SI.loc['Average']['October']
y_dm[34] = y_dm[34]/SI.loc['Average']['November']
y_dm[35] = y_dm[35]/SI.loc['Average']['December']
y_dm[36] = y_dm[36]/SI.loc['Average']['January']
y_dm[37] = y_dm[37]/SI.loc['Average']['February']
y_dm[38] = y_dm[38]/SI.loc['Average']['March']
y_dm[39] = y_dm[39]/SI.loc['Average']['April']
y_dm[40] = y_dm[40]/SI.loc['Average']['May']
y_dm[41] = y_dm[41]/SI.loc['Average']['June']
y_dm[42] = y_dm[42]/SI.loc['Average']['July']
y_dm[43] = y_dm[43]/SI.loc['Average']['August']
y_dm[44] = y_dm[44]/SI.loc['Average']['September']
y_dm[45] = y_dm[45]/SI.loc['Average']['October']
y_dm[46] = y_dm[46]/SI.loc['Average']['November']
y_dm[47] = y_dm[47]/SI.loc['Average']['December']
print("y = ",y_dm)

y =  [383382.4561403509 315110.7438016529 359545.7875457875 408620.84942084947
 792682.8571428572 656692.1212121212 669885.9060402684 457887.3786407767
 391642.36453201965 313859.92217898834 363125.1461988304
 230656.38297872336 423723.97660818713 305008.26446280995
 342412.4542124542 406650.1930501931 796828.5714285715 610202.4242424243
 652991.9463087247 447821.35922330094 412161.57635467977 320540.0778210117
 350520.4678362573 231845.74468085103 413912.2807017544 317925.6198347107
 321852.74725274724 249000.77220077222 625564.2857142858 581745.4545454546
 680322.1476510066 456166.01941747573 454147.7832512315 348148.63813229575
 364128.6549707602 260321.27659574462 396830.40935672517
 252664.46280991737 310169.9633699634 362379.1505791506 684814.2857142858
 629129.696969697 697263.0872483221 454691.2621359223 427777.3399014778
 315528.4046692607 368624.56140350876 228909.57446808508]


Perform simple linear regression to extract trend.

In [10]:
model_dm = LinearRegression()
x = np.arange(1, 49).reshape((-1, 1))
model_dm.fit(x,y_dm)
r_sq_dm = model_dm.score(x, y_dm)
print('Coefficient of determination:', r_sq_dm)
intercept_dm = model_dm.intercept_
print('Intercept:', intercept_dm)
slope_dm = model_dm.coef_[0]
print('Slope:', slope_dm)

Coefficient of determination: 0.007336645939195252
Intercept: 457498.07936610846
Slope: -947.3562573264942


Extend the trend to year 5. 

In [11]:
#The forecast calculation is explicitly stated here but you can use sklearn's Predict function, as well (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).
forecast_dm = []
for t in range(49,61):
    forecast_dm.append(intercept_dm + t*slope_dm)
forecast_dm

[411077.6227571102,
 410130.2664997837,
 409182.91024245723,
 408235.55398513074,
 407288.19772780425,
 406340.84147047775,
 405393.48521315126,
 404446.12895582477,
 403498.7726984983,
 402551.4164411718,
 401604.0601838453,
 400656.7039265188]

Seasonalize year 5 forecasts.

In [12]:
forecast_dm[0] = forecast_dm[0]*SI.loc['Average']['January']
forecast_dm[1] = forecast_dm[1]*SI.loc['Average']['February']
forecast_dm[2] = forecast_dm[2]*SI.loc['Average']['March']
forecast_dm[3] = forecast_dm[3]*SI.loc['Average']['April']
forecast_dm[4] = forecast_dm[4]*SI.loc['Average']['May']
forecast_dm[5] = forecast_dm[5]*SI.loc['Average']['June']
forecast_dm[6] = forecast_dm[6]*SI.loc['Average']['July']
forecast_dm[7] = forecast_dm[7]*SI.loc['Average']['August']
forecast_dm[8] = forecast_dm[8]*SI.loc['Average']['September']
forecast_dm[9] = forecast_dm[9]*SI.loc['Average']['October']
forecast_dm[10] = forecast_dm[10]*SI.loc['Average']['November']
forecast_dm[11] = forecast_dm[11]*SI.loc['Average']['December']
forecast_dm

[351471.36745732924,
 496257.6224647383,
 558534.6724809541,
 528665.0424107442,
 285101.73840946297,
 335231.19421314413,
 302018.14648379775,
 416579.5128244995,
 409551.2542889758,
 517278.5701269057,
 343371.4714571877,
 376617.3016909277]

# Forecast Using Multiple Linear Regression

Populate independent variables

In [13]:
x = np.arange(1, 49).reshape((-1, 1))#Must change this to add the dummy binary variables.
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48]])

Run multiple linear regression.

In [14]:
model_mlr = LinearRegression()
model_mlr.fit(x,y_dm) #Must change this. Basically, you need to extend the simple linear regression model to take multiple independent variables. You are referred to https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html for the documentation of the package we use for this purpose. Make sure you use the correct y values, too.

LinearRegression()

Calculate the forecasts.

In [15]:
forecast_mlr = []
#Must add this. Decide first whether you want to calculate the forecasts explicitly or via sklearn's Predict function (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) and then execute.
forecast_mlr

[]

# Calculate Forecast Accuracy

In [16]:
actual_Year5 = []
for t in range(53,61):
    actual_Year5.append(row[t])
actual_Year5

[253159.0, 284434.0, 385837.0, 417512.0, 440501.0, 474768.0, 409400.0, 361392]

In [17]:
deviation_dm = []
deviation_mlr = []
for t in range(8):
    deviation_dm.append(np.random.normal(0,1,1)) #Must change this, it is curently just random
    deviation_mlr.append(np.random.normal(0,1,1)) #Must change this, it is curently just random
MAD_dm = pf.CalculateMeanAbsoluteDeviation(deviation_dm)
MAD_mlr = pf.CalculateMeanAbsoluteDeviation(deviation_mlr)
print("MAD_DM:",MAD_dm)
print("MAD_MLR:",MAD_mlr)

MAD_DM: 0.5681207977180651
MAD_MLR: 0.7703298505811399
